COMPONENT=TestC

CFLAGS += -I$(TOSDIR)/lib/net
CFLAGS += -I$(TOSDIR)/lib/net/zonedip -I$(TOSDIR)/lib/net/zonedip/interfaces
CFLAGS += -I$(TOSDIR)/lib/net/neighbors -I$(TOSDIR)/lib/net/neighbors/interfaces
CFLAGS += -I$(TOSDIR)/lib/actuator -I$(TOSDIR)/lib/actuator/interfaces
CFLAGS += -I$(TOSDIR)/lib/actuator/zone -I$(TOSDIR)/lib/actuator/zone/interfaces

CFLAGS += -DTOSH_DATA_LENGTH=48

include $(MAKERULES)

